package zone.moddev.mc.skysbuildingpieces.legacy;

import java.util.*;
import net.minecraft.block.state.IBlockState;
import net.minecraft.entity.*;
import net.minecraft.entity.item.*;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.inventory.IInventory;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.*;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.chunk.Chunk;
import net.minecraftforge.event.entity.EntityJoinWorldEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.event.world.*;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.items.*;
import zone.moddev.mc.skysbuildingpieces.catalogue.*;

public final class MigrationEvents {
    private int ticks;
    private final java.util.Queue<Chunk> pending=new java.util.concurrent.ConcurrentLinkedQueue<Chunk>();
    private final Map<Chunk,NBTTagCompound> coverage=Collections.synchronizedMap(new WeakHashMap<Chunk,NBTTagCompound>());
    @SubscribeEvent public void load(ChunkDataEvent.Load e) {
        if(e.getWorld().isRemote)return;
        NBTTagCompound n=e.getData(),level=n.getCompoundTag("Level");
        // Turning replacement off must retain existing module markers, while
        // leaving previously unvisited chunks entirely unmarked.
        if(level.hasKey("skysbuildingpieces_coverage",10))coverage.put(e.getChunk(),level.getCompoundTag("skysbuildingpieces_coverage").copy());
        if(!LegacyBridge.active())return;
        if(!coverage.containsKey(e.getChunk()))coverage.put(e.getChunk(),new NBTTagCompound());
        // Raw recovery changes the compound before constructing the Chunk.
        // That constructor does not know it must persist the recovered data.
        // Mark storage dirty explicitly, without any neighbour notifications.
        e.getChunk().setChunkModified();
        if(n.hasKey("skysbuildingpieces_delta")) {
            PiecesWorldState s=PiecesWorldState.get(e.getWorld());s.blocks+=n.getLong("skysbuildingpieces_delta");s.chunks++;s.markDirty();n.removeTag("skysbuildingpieces_delta");
        }
        if(n.hasKey("skysbuildingpieces_module_delta",10)) {
            PiecesWorldState s=PiecesWorldState.get(e.getWorld());NBTTagCompound deltas=n.getCompoundTag("skysbuildingpieces_module_delta");
            for(String module:deltas.getKeySet())s.addChunk(module,deltas.getLong(module));
            s.markDirty();n.removeTag("skysbuildingpieces_module_delta");
        }
        pending.add(e.getChunk());
        LegacyBridge.report(e.getWorld());
    }
    @SubscribeEvent public void tick(net.minecraftforge.fml.common.gameevent.TickEvent.ServerTickEvent e) {
        if(e.phase!=net.minecraftforge.fml.common.gameevent.TickEvent.Phase.END || !LegacyBridge.active())return;
        for(int count=0;count<8;count++) {Chunk chunk=pending.poll();if(chunk==null)break;
            for(TileEntity tile:new ArrayList<TileEntity>(chunk.getTileEntityMap().values())) {
                // Unopened loot containers must not have their loot generated by migration.
                NBTTagCompound raw=tile.writeToNBT(new NBTTagCompound());if(raw.hasKey("LootTable",8))continue;
                containers(tile);
            }
        }
        if(++ticks%100==0 && LegacyBridge.hasPendingReport()) {
            net.minecraft.server.MinecraftServer server=net.minecraftforge.fml.common.FMLCommonHandler.instance().getMinecraftServerInstance();
            if(server!=null)LegacyBridge.report(server.worldServerForDimension(0));
        }
    }
    @SubscribeEvent public void unload(WorldEvent.Unload e) {
        if(e.getWorld().isRemote)return;
        if(LegacyBridge.active() && LegacyBridge.hasPendingReport())LegacyBridge.report(e.getWorld());
        pending.removeIf(c->c.getWorld()==e.getWorld());
        synchronized(coverage){coverage.keySet().removeIf(c->c.getWorld()==e.getWorld());}
    }
    @SubscribeEvent public void save(ChunkDataEvent.Save e) {
        NBTTagCompound c=coverage.get(e.getChunk());if(c!=null)e.getData().getCompoundTag("Level").setTag("skysbuildingpieces_coverage",c.copy());
    }
    @SubscribeEvent public void placed(BlockEvent.PlaceEvent e) {
        if(e.getWorld().isRemote || !LegacyBridge.active())return;
        BlockPos p=e.getPos();IBlockState old=e.getWorld().getBlockState(p);
        String id=old.getBlock().getRegistryName().toString();if(!LegacyMapping.owned(id))return;
        TileEntity tile=e.getWorld().getTileEntity(p);if(tile==null)return;
        NBTTagCompound n=tile.writeToNBT(new NBTTagCompound());Shape shape=LegacyMapping.shape(id,old.getBlock().getMetaFromState(old));
        IBlockState target=LegacyBridge.resolve(id,LegacyMapping.material(n.getString("material")),shape,LegacyMapping.orientation(shape,old.getBlock().getMetaFromState(old)));
        if(target!=null && e.getWorld().setBlockState(p,target,3)) {
            Chunk chunk=e.getWorld().getChunkFromBlockCoords(p);
            NBTTagCompound c=coverage.get(chunk);if(c==null){c=new NBTTagCompound();coverage.put(chunk,c);}
            NBTTagList retained=c.getTagList("retained_tiles",10);retained.appendTag(n.copy());c.setTag("retained_tiles",retained);
            PiecesWorldState s=PiecesWorldState.get(e.getWorld());s.addBlocks(Catalogue.INSTANCE.moduleFor(LegacyMapping.material(n.getString("material"))),1);s.markDirty();
        }
    }
    @SubscribeEvent public void entity(EntityJoinWorldEvent e) {
        if(e.getWorld().isRemote || !LegacyBridge.active())return;
        Entity entity=e.getEntity();
        if(entity instanceof EntityPlayer) {EntityPlayer p=(EntityPlayer)entity;inventory(p.inventory);inventory(p.getInventoryEnderChest());}
        if(entity instanceof EntityItem) {EntityItem item=(EntityItem)entity;item.setEntityItemStack(convert(item.getEntityItem(),e.getWorld()));}
        if(entity instanceof EntityItemFrame){EntityItemFrame f=(EntityItemFrame)entity;f.setDisplayedItem(convert(f.getDisplayedItem(),e.getWorld()));}
        if(entity instanceof IInventory)inventory((IInventory)entity);
    }
    @SubscribeEvent public void player(PlayerEvent.LoadFromFile e) { if(LegacyBridge.active()) {inventory(e.getEntityPlayer().inventory);inventory(e.getEntityPlayer().getInventoryEnderChest());} }
    private static void inventory(IInventory inv) {for(int i=0;i<inv.getSizeInventory();i++){ItemStack old=inv.getStackInSlot(i),updated=convert(old,null);if(updated!=old){inv.setInventorySlotContents(i,updated);inv.markDirty();}}}
    private static void containers(TileEntity tile) {
        if(tile instanceof IInventory)inventory((IInventory)tile);
        Set<IItemHandler> handled=Collections.newSetFromMap(new IdentityHashMap<IItemHandler,Boolean>());
        for(EnumFacing face:new EnumFacing[]{null,EnumFacing.DOWN,EnumFacing.UP,EnumFacing.NORTH,EnumFacing.SOUTH,EnumFacing.EAST,EnumFacing.WEST})if(tile.hasCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY,face)) {
            IItemHandler handler=tile.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY,face);
            if(handler instanceof IItemHandlerModifiable && handled.add(handler))for(int slot=0;slot<handler.getSlots();slot++){ItemStack old=handler.getStackInSlot(slot),updated=convert(old,tile.getWorld());if(updated!=old){((IItemHandlerModifiable)handler).setStackInSlot(slot,updated);tile.markDirty();}}
        }
    }
    public static ItemStack convert(ItemStack old,net.minecraft.world.World world) {
        if(old==null || !LegacyBridge.active())return old;
        NBTTagCompound before=old.writeToNBT(new NBTTagCompound()),n=before.copy();LegacyBridge.prepareStack(n);
        if(n.equals(before))return old;
        ItemStack updated=ItemStack.loadItemStackFromNBT(n);
        return updated;
    }
}
